/*
 * Class : FDISystemAdminWorkAreaJPanel.java
 * Developer : Laksh Lumba
 * Reviewer :
 * Description : 
 * Created On : Nov 11, 2014, 11:45:15 PM
 * ---------------------------------------------------------------------------
 * Change History
 * Develper :
 * Reviwer :
 * Changed ON :
 * ---------------------------------------------------------------------------
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drugsupplychain.neu.css.gui.regional.lawagency.pharma;

import drugsupplychain.neu.css.gui.common.panel.ManagePharmaCoLisenceJPanel;
import drugsupplychain.neu.css.gui.common.lawAgency.pharma.ManagePharmaProductJPanel;
import drugsupplychain.neu.css.gui.common.lawAgency.pharma.ManagePharmaRequestsJPanel;
import drugsupplychain.neu.css.gui.common.panel.RegisterPharmaOrganizationJPanel;
import drugsupplychain.neu.css.model.organization.Organization.Type;
import drugsupplychain.neu.css.model.organization.lawAgencies.RegionalLawAgency;
import drugsupplychain.neu.css.model.organization.pharmacompany.RegionalPharmaceauticalCompany;
import drugsupplychain.neu.css.model.organization.pharmacompany.RegionalPharmaceauticalCompanyDirectory;
import drugsupplychain.neu.css.model.request.WorkRequest;
import drugsupplychain.neu.css.util.ImplConst;
import drugsupplychain.neu.css.util.ImplValidationUtils;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Laksh
 */
public class ManageRegionalPharmaCompanyJPanel extends javax.swing.JPanel {
    private final JPanel userProcessContainer;
    private final RegionalPharmaceauticalCompanyDirectory regionalPharmaceauticalCompanyDirectory;
    private final RegionalLawAgency regionalLawAgency;
    /**
     * Creates new form ManageRegionalPharmaCompanyJPanel
     * @param userProcessContainer
     * @param regionalLawAgency
     */
    public ManageRegionalPharmaCompanyJPanel(JPanel userProcessContainer,RegionalLawAgency regionalLawAgency) {
        initComponents();
        this.regionalPharmaceauticalCompanyDirectory = regionalLawAgency.getRegionalPharmaceauticalCompanyDirectory();
        this.userProcessContainer = userProcessContainer;
        this.regionalLawAgency = regionalLawAgency;
        populateTable();
        populateNotification();
    }
    private void populateNotification(){
        int notification = 0;
        for (RegionalPharmaceauticalCompany regionalPharmaceauticalCompany : regionalPharmaceauticalCompanyDirectory.getRegionalPharmaceauticalCompanyList()){
            for(WorkRequest workRequest : regionalPharmaceauticalCompany.getWorkQueue().getWorkRequestList()){
                if(workRequest.getStatus().equals(ImplConst.CASE_NEW)){
                    notification++;
                }
            }      
        }
        notificationLabel.setText(String.valueOf(notification));
    }
    private void populateTable(){
        DefaultTableModel defaultTableModel = (DefaultTableModel)pharmaTable.getModel();
        defaultTableModel.setRowCount(0);
        for (RegionalPharmaceauticalCompany regionalPharmaceauticalCompany : regionalPharmaceauticalCompanyDirectory.getRegionalPharmaceauticalCompanyList()){
            Object[] row = new Object[4];
            row[0] = regionalPharmaceauticalCompany;
            row[1] = regionalPharmaceauticalCompany.getOrganizationID();
            row[2] = regionalPharmaceauticalCompany.getLincense().getLicenseNumber();
            row[3] = regionalPharmaceauticalCompany.getLincense().isIsLicenseValid();
            defaultTableModel.addRow(row);            
        }
    }
    
    private void populateTable(int pharmaId){
        DefaultTableModel defaultTableModel = (DefaultTableModel)pharmaTable.getModel();
        defaultTableModel.setRowCount(0);
        for (RegionalPharmaceauticalCompany regionalPharmaceauticalCompany : regionalPharmaceauticalCompanyDirectory.getRegionalPharmaceauticalCompanyList()){
            if (regionalPharmaceauticalCompany.getOrganizationID()== pharmaId){
                Object[] row = new Object[4];
                row[0] = regionalPharmaceauticalCompany;
                row[1] = regionalPharmaceauticalCompany.getOrganizationID();
                row[2] = regionalPharmaceauticalCompany.getLincense().getLicenseNumber();
                row[3] = regionalPharmaceauticalCompany.getLincense().isIsLicenseValid();
                defaultTableModel.addRow(row);            
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageLisenceButton = new javax.swing.JButton();
        managePharmaProductButton = new javax.swing.JButton();
        managePharmaCoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pharmaTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        pharmaIdTextField = new javax.swing.JTextField();
        searchByIdButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        managePharmaProductButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        notificationLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Manage Inter Pharama Co.");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        manageLisenceButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        manageLisenceButton.setText("Manage License ");
        manageLisenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageLisenceButtonActionPerformed(evt);
            }
        });
        add(manageLisenceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 170, 50));

        managePharmaProductButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        managePharmaProductButton.setText("Manage Requests");
        managePharmaProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePharmaProductButtonActionPerformed(evt);
            }
        });
        add(managePharmaProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, 50));

        managePharmaCoButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        managePharmaCoButton.setText("Register Pharma Co. ");
        managePharmaCoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePharmaCoButtonActionPerformed(evt);
            }
        });
        add(managePharmaCoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 180, 50));

        pharmaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pharmaceautical Name", "PharmaId", "License Number", "Is License Valid"
            }
        ));
        jScrollPane1.setViewportView(pharmaTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 730, 160));

        backButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/back.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 110, 40));
        add(pharmaIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 120, 30));

        searchByIdButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        searchByIdButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/searchicon.png"))); // NOI18N
        searchByIdButton.setText("Search By Id");
        searchByIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByIdButtonActionPerformed(evt);
            }
        });
        add(searchByIdButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, 30));

        refreshButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/refresh.png"))); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        managePharmaProductButton1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        managePharmaProductButton1.setText("Manage Pharma Product");
        managePharmaProductButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePharmaProductButton1ActionPerformed(evt);
            }
        });
        add(managePharmaProductButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.add(notificationLabel);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 20, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void managePharmaCoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePharmaCoButtonActionPerformed
       RegisterPharmaOrganizationJPanel registerPharmaCOJPanel = new RegisterPharmaOrganizationJPanel(userProcessContainer,regionalPharmaceauticalCompanyDirectory,regionalLawAgency,Type.REGIONAL_PHARMA_CO);
       userProcessContainer.add("RegisterPharmaCOJPanel",registerPharmaCOJPanel);
       CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
       cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_managePharmaCoButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchByIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByIdButtonActionPerformed
        if(validateFields()){
            int pharmaId = Integer.parseInt(pharmaIdTextField.getText());
            populateTable(pharmaId);
        }
    }//GEN-LAST:event_searchByIdButtonActionPerformed

    private void manageLisenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageLisenceButtonActionPerformed
        int selectedRow =  pharmaTable.getSelectedRow();
        if (selectedRow < 0 ){
            JOptionPane.showMessageDialog(null, "Please select the row from the list");
        } else {
            RegionalPharmaceauticalCompany regionalPharmaceauticalCompany = (RegionalPharmaceauticalCompany)pharmaTable.getValueAt(selectedRow, 0);
            ManagePharmaCoLisenceJPanel managePharmaCoLisenceJPanel =  new ManagePharmaCoLisenceJPanel(userProcessContainer,regionalPharmaceauticalCompany,Type.REGIONAL_PHARMA_CO);
            userProcessContainer.add("ManagePharmaCoLisenceJPanel",managePharmaCoLisenceJPanel);
            CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);
        }  
    }//GEN-LAST:event_manageLisenceButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        populateTable();
        populateNotification();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void managePharmaProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePharmaProductButtonActionPerformed
        int selectedRow =  pharmaTable.getSelectedRow();
        if (selectedRow < 0 ){
            JOptionPane.showMessageDialog(null, "Please select the row from the list");
        } else {
            RegionalPharmaceauticalCompany regionalPharmaceauticalCompany = (RegionalPharmaceauticalCompany)pharmaTable.getValueAt(selectedRow, 0);
            ManagePharmaRequestsJPanel managePharmaRequestsJPanel =  new ManagePharmaRequestsJPanel(userProcessContainer,regionalPharmaceauticalCompany);
            userProcessContainer.add("ManagePharmaRequestsJPanel",managePharmaRequestsJPanel);
            CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);
        }  
    }//GEN-LAST:event_managePharmaProductButtonActionPerformed

    private void managePharmaProductButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePharmaProductButton1ActionPerformed
        int selectedRow =  pharmaTable.getSelectedRow();
        if (selectedRow < 0 ){
            JOptionPane.showMessageDialog(null, "Please select the row from the list");
        } else {
            RegionalPharmaceauticalCompany regionalPharmaceauticalCompany = (RegionalPharmaceauticalCompany)pharmaTable.getValueAt(selectedRow, 0);
            ManagePharmaProductJPanel managePharmaProductJPanel =  new ManagePharmaProductJPanel(userProcessContainer,regionalPharmaceauticalCompany.getProductCatalog(),regionalPharmaceauticalCompany);
            userProcessContainer.add("ManagePharmaProductJPanel",managePharmaProductJPanel);
            CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);
        }
    }//GEN-LAST:event_managePharmaProductButton1ActionPerformed
     /**
     * validate the fields before submitting
     */
    private boolean validateFields(){        
        StringBuffer validationMessage = new StringBuffer();
        boolean isValidationPassed = true;
        if(!ImplValidationUtils.isInteger(pharmaIdTextField.getText())){
            validationMessage.append(ImplConst.VALIDATE_INTEGER_VALUE);
            validationMessage.append(ImplConst.NEXT_LINE);
            isValidationPassed = false;
        }
        if(!isValidationPassed){
            JOptionPane.showMessageDialog(null,validationMessage);
        } 
        return isValidationPassed;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageLisenceButton;
    private javax.swing.JButton managePharmaCoButton;
    private javax.swing.JButton managePharmaProductButton;
    private javax.swing.JButton managePharmaProductButton1;
    private javax.swing.JLabel notificationLabel;
    private javax.swing.JTextField pharmaIdTextField;
    private javax.swing.JTable pharmaTable;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton searchByIdButton;
    // End of variables declaration//GEN-END:variables
}
