/*
 * Class : CityLawAgencyWorkAreaJPanel.java
 * Developer : Laksh Lumba
 * Reviewer :
 * Description : 
 * Created On : Nov 11, 2014, 11:45:15 PM
 * ---------------------------------------------------------------------------
 * Change History
 * Develper :
 * Reviwer :
 * Changed ON :
 * ---------------------------------------------------------------------------
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drugsupplychain.neu.css.gui.city.lawagency;

import drugsupplychain.neu.css.gui.city.lawagency.distributors.ManageCityDistributorsJPanel;
import drugsupplychain.neu.css.gui.common.lawAgency.FDI.CraeteCaseRequestsJPanel;
import drugsupplychain.neu.css.gui.common.panel.UpdateContactJPanel;
import drugsupplychain.neu.css.log.ImplLogger;
import drugsupplychain.neu.css.model.organization.lawAgencies.CityLawAgency;
import drugsupplychain.neu.css.model.organization.lawAgencies.StateLawAgency;
import drugsupplychain.neu.css.model.user.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Laksh
 */
public class CityLawAgencyWorkAreaJPanel extends javax.swing.JPanel {
    private final JPanel userProcessContainer;
    private final UserAccount userAccount;
    private final StateLawAgency stateLawAgency;
    private final CityLawAgency cityLawAgency;
    /**
     * Creates new form StateLawAgencyWorkAreaJPanel
     * @param userProcessContainer
     * @param userAccount
     * @param cityLawAgency
     * @param stateLawAgency
     */
    public CityLawAgencyWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount,CityLawAgency cityLawAgency,StateLawAgency stateLawAgency) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.stateLawAgency = stateLawAgency;
        this.cityLawAgency = cityLawAgency;
        populateAddressInfo();
    }
    /**
     * populate the address info
     */
    private void populateAddressInfo(){
        userNameLabel.setText(userAccount.getUsername());
        address1Label.setText(userAccount.getPerson().getAddress().getAddressLine1());
        address2Label.setText(userAccount.getPerson().getAddress().getAddressLine2());
        cityLabel.setText(userAccount.getPerson().getAddress().getCity());
        stateLabel.setText(userAccount.getPerson().getAddress().getState());
        nationLabel.setText(userAccount.getPerson().getAddress().getCountry());
        zipLabel.setText(userAccount.getPerson().getAddress().getZipcode());
        emailLabel.setText(userAccount.getPerson().getEmail());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        updateContact = new javax.swing.JButton();
        manageCityDistributor = new javax.swing.JButton();
        manageOrganization = new javax.swing.JButton();
        manageOrganization1 = new javax.swing.JButton();
        address2Label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        address1Label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        zipLabel = new javax.swing.JLabel();
        nationLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        fdiProcessContainerPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSplitPane1.setDividerLocation(200);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        updateContact.setBackground(new java.awt.Color(255, 255, 255));
        updateContact.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        updateContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/Folder.png"))); // NOI18N
        updateContact.setText("Update Contact");
        updateContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateContactActionPerformed(evt);
            }
        });

        manageCityDistributor.setBackground(new java.awt.Color(255, 255, 255));
        manageCityDistributor.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        manageCityDistributor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/Folder.png"))); // NOI18N
        manageCityDistributor.setText("City Distributor");
        manageCityDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCityDistributorActionPerformed(evt);
            }
        });

        manageOrganization.setBackground(new java.awt.Color(255, 255, 255));
        manageOrganization.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        manageOrganization.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/Folder.png"))); // NOI18N
        manageOrganization.setText("Manage Organizations");
        manageOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationActionPerformed(evt);
            }
        });

        manageOrganization1.setBackground(new java.awt.Color(255, 255, 255));
        manageOrganization1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        manageOrganization1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/Folder.png"))); // NOI18N
        manageOrganization1.setText("Create Case");
        manageOrganization1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganization1ActionPerformed(evt);
            }
        });

        address2Label.setText("address2");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel7.setText("Zip Code:");

        address1Label.setText("address1");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel6.setText("Country:");

        userNameLabel.setText("user");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel5.setText("State:");

        jLabel2.setBackground(new java.awt.Color(102, 102, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Address:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel4.setText("City:");

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("Username:");

        emailLabel.setText("email");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel10.setText("Email : ");

        zipLabel.setText("zip");

        nationLabel.setText("nation");

        stateLabel.setText("state");

        cityLabel.setText("city");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(manageCityDistributor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageOrganization, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageOrganization1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(updateContact))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zipLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nationLabel))
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(userNameLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cityLabel)
                                    .addComponent(stateLabel)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(address1Label)
                                .addGap(24, 24, 24)
                                .addComponent(address2Label)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageCityDistributor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageOrganization)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageOrganization1)
                .addGap(68, 68, 68)
                .addComponent(updateContact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userNameLabel))
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(address2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(address1Label)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cityLabel))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(stateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nationLabel))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(zipLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(emailLabel))
                .addGap(49, 49, 49))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        fdiProcessContainerPanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout fdiProcessContainerPanelLayout = new javax.swing.GroupLayout(fdiProcessContainerPanel);
        fdiProcessContainerPanel.setLayout(fdiProcessContainerPanelLayout);
        fdiProcessContainerPanelLayout.setHorizontalGroup(
            fdiProcessContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        fdiProcessContainerPanelLayout.setVerticalGroup(
            fdiProcessContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(fdiProcessContainerPanel);

        add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -5, 1170, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void updateContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateContactActionPerformed
       ImplLogger.enterMethod();
       UpdateContactJPanel updateContactJPanel = new UpdateContactJPanel(userProcessContainer,cityLawAgency);
       userProcessContainer.add("UpdateContactJPanel",updateContactJPanel);
       CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
       cardLayout.next(userProcessContainer);
       ImplLogger.exitMethod();
    }//GEN-LAST:event_updateContactActionPerformed

    private void manageOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationActionPerformed
       ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer,userAccount,cityLawAgency,stateLawAgency);
       userProcessContainer.add("ManageOrganizationJPanel",manageOrganizationJPanel);
       CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
       cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationActionPerformed

    private void manageCityDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCityDistributorActionPerformed
       ManageCityDistributorsJPanel manageCityDistributorsJPanel = new ManageCityDistributorsJPanel(userProcessContainer,cityLawAgency);
       userProcessContainer.add("ManageCityDistributorsJPanel",manageCityDistributorsJPanel);
       CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
       cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_manageCityDistributorActionPerformed

    private void manageOrganization1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganization1ActionPerformed
       CraeteCaseRequestsJPanel craeteCaseRequestsJPanel = new CraeteCaseRequestsJPanel(userProcessContainer,userAccount,cityLawAgency);
       userProcessContainer.add("CraeteCaseRequestsJPanel",craeteCaseRequestsJPanel);
       CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
       cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganization1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address1Label;
    private javax.swing.JLabel address2Label;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel fdiProcessContainerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton manageCityDistributor;
    private javax.swing.JButton manageOrganization;
    private javax.swing.JButton manageOrganization1;
    private javax.swing.JLabel nationLabel;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JButton updateContact;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel zipLabel;
    // End of variables declaration//GEN-END:variables
}
