/*
 * Class : ManageOrganizationJPanel.java
 * Developer : Laksh Lumba
 * Reviewer :
 * Description : 
 * Created On : Nov 19, 2014, 8:55:57 PM
 * ---------------------------------------------------------------------------
 * Change History
 * Develper :
 * Reviwer :
 * Changed ON :
 * ---------------------------------------------------------------------------
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drugsupplychain.neu.css.gui.city.lawagency;

import drugsupplychain.neu.css.gui.city.lawagency.clinics.ManageCityClinicsJPanel;
import drugsupplychain.neu.css.gui.city.lawagency.dispenseries.ManageCityDispenseriesJPanel;
import drugsupplychain.neu.css.gui.city.lawagency.doctors.ManageCityDoctorsJPanel;
import drugsupplychain.neu.css.gui.city.lawagency.hospitals.ManageCityHospitalsJPanel;
import drugsupplychain.neu.css.gui.city.lawagency.pharmacies.ManageCityPharmaciesJPanel;
import drugsupplychain.neu.css.log.ImplLogger;
import drugsupplychain.neu.css.model.organization.lawAgencies.CityLawAgency;
import drugsupplychain.neu.css.model.organization.lawAgencies.StateLawAgency;
import drugsupplychain.neu.css.model.user.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Laksh
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {
private final JPanel userProcessContainer;
    private final UserAccount userAccount;
    private final StateLawAgency stateLawAgency;
    private final CityLawAgency cityLawAgency;
    /**
     * Creates new form ManageOrganizationJPanel
     * @param userProcessContainer
     * @param userAccount
     * @param cityLawAgency
     * @param stateLawAgency
     */
    public ManageOrganizationJPanel(JPanel userProcessContainer, UserAccount userAccount,CityLawAgency cityLawAgency,StateLawAgency stateLawAgency) {
        initComponents();
        ImplLogger.enterMethod();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.stateLawAgency = stateLawAgency;
        this.cityLawAgency = cityLawAgency;
        ImplLogger.exitMethod();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managePharmacies = new javax.swing.JButton();
        manageClinicsButton = new javax.swing.JButton();
        manageHospitals = new javax.swing.JButton();
        managePatientButton = new javax.swing.JButton();
        manageDispenseriesButton = new javax.swing.JButton();
        manageDoctorsButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        managePharmacies.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        managePharmacies.setText("Manage City Pharmacies");
        managePharmacies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePharmaciesActionPerformed(evt);
            }
        });

        manageClinicsButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        manageClinicsButton.setText("Manage City Clinics");
        manageClinicsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageClinicsButtonActionPerformed(evt);
            }
        });

        manageHospitals.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        manageHospitals.setText("Manage City Hospitals");
        manageHospitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageHospitalsActionPerformed(evt);
            }
        });

        managePatientButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        managePatientButton.setText("Manage City Patient");
        managePatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePatientButtonActionPerformed(evt);
            }
        });

        manageDispenseriesButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        manageDispenseriesButton.setText("Manage City Dispenseries");
        manageDispenseriesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDispenseriesButtonActionPerformed(evt);
            }
        });

        manageDoctorsButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        manageDoctorsButton.setText("Manage Doctors");
        manageDoctorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDoctorsButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/back.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Manage City Organizations ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageDoctorsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(managePatientButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageDispenseriesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageClinicsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(managePharmacies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageHospitals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageHospitals, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(managePharmacies, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageClinicsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageDispenseriesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(managePatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(manageDoctorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * back button
     * @param evt 
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        ImplLogger.enterMethod();
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        ImplLogger.exitMethod();
    }//GEN-LAST:event_backButtonActionPerformed
    /**
     * manage hospital
     * @param evt 
     */
    private void manageHospitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageHospitalsActionPerformed
       ImplLogger.enterMethod();
       ManageCityHospitalsJPanel manageCityHospitalsJPanel = new ManageCityHospitalsJPanel(userProcessContainer,cityLawAgency);
       userProcessContainer.add("ManageCityHospitalsJPanel",manageCityHospitalsJPanel);
       CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
       cardLayout.next(userProcessContainer);
       ImplLogger.exitMethod();
    }//GEN-LAST:event_manageHospitalsActionPerformed
    /**
     * manage pharmacies
     * @param evt 
     */
    private void managePharmaciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePharmaciesActionPerformed
       ImplLogger.enterMethod();
       ManageCityPharmaciesJPanel manageCityPharmaciesJPanel = new ManageCityPharmaciesJPanel(userProcessContainer,cityLawAgency);
       userProcessContainer.add("ManageCityPharmaciesJPanel",manageCityPharmaciesJPanel);
       CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
       cardLayout.next(userProcessContainer);
       ImplLogger.exitMethod();
    }//GEN-LAST:event_managePharmaciesActionPerformed
    /**
     * manage clinic
     * @param evt 
     */
    private void manageClinicsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageClinicsButtonActionPerformed
       ImplLogger.enterMethod();
       ManageCityClinicsJPanel manageCityClinicsJPanel = new ManageCityClinicsJPanel(userProcessContainer,cityLawAgency);
       userProcessContainer.add("ManageCityClinicsJPanel",manageCityClinicsJPanel);
       CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
       cardLayout.next(userProcessContainer);
       ImplLogger.exitMethod();
    }//GEN-LAST:event_manageClinicsButtonActionPerformed
    /**
     * manage dispensary
     * @param evt 
     */
    private void manageDispenseriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDispenseriesButtonActionPerformed
       ManageCityDispenseriesJPanel manageCityDispenseriesJPanel = new ManageCityDispenseriesJPanel(userProcessContainer,cityLawAgency);
       userProcessContainer.add("ManageCityDispenseriesJPanel",manageCityDispenseriesJPanel);
       CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
       cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_manageDispenseriesButtonActionPerformed
    /**
     * manage pattern
     * @param evt 
     */
    private void managePatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePatientButtonActionPerformed
       ManageCityPatientJPanel manageCityPatientJPanel = new ManageCityPatientJPanel(userProcessContainer,cityLawAgency,cityLawAgency);
       userProcessContainer.add("ManageCityPatientJPanel",manageCityPatientJPanel);
       CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
       cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_managePatientButtonActionPerformed
    /**
     * manage  doctors
     * @param evt 
     */
    private void manageDoctorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDoctorsButtonActionPerformed
       ManageCityDoctorsJPanel manageCityDoctorsJPanel = new ManageCityDoctorsJPanel(userProcessContainer,cityLawAgency);
       userProcessContainer.add("ManageCityDoctorsJPanel",manageCityDoctorsJPanel);
       CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
       cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_manageDoctorsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageClinicsButton;
    private javax.swing.JButton manageDispenseriesButton;
    private javax.swing.JButton manageDoctorsButton;
    private javax.swing.JButton manageHospitals;
    private javax.swing.JButton managePatientButton;
    private javax.swing.JButton managePharmacies;
    // End of variables declaration//GEN-END:variables
}
