/*
 * Class : ManageRegionalCasesJPanel.java
 * Developer : Laksh Lumba
 * Reviewer :
 * Description : 
 * Created On : Nov 12, 2014, 9:39:42 PM
 * ---------------------------------------------------------------------------
 * Change History
 * Develper :
 * Reviwer :
 * Changed ON :
 * ---------------------------------------------------------------------------
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drugsupplychain.neu.css.gui.city.lawagency;

import drugsupplychain.neu.css.model.organization.Organization;
import drugsupplychain.neu.css.model.organization.lawAgencies.CityLawAgency;
import drugsupplychain.neu.css.model.product.Product;
import drugsupplychain.neu.css.model.product.ProductCase;
import drugsupplychain.neu.css.model.request.DrugCaseRequest;
import drugsupplychain.neu.css.model.request.WorkRequest;
import drugsupplychain.neu.css.model.user.UserAccount;
import drugsupplychain.neu.css.util.ImplCommonUtil;
import drugsupplychain.neu.css.util.ImplConst;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Laksh
 */
public class ManageRequestAgainstMedicationJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final Organization organization;
    private final UserAccount userAccount;
    private final CityLawAgency cityLawAgency;
    /**
     * Creates new form ManageRequestsJPanel
     * @param userProcessContainer
     * @param organization
     * @param cityLawAgency
     */
    public ManageRequestAgainstMedicationJPanel(JPanel userProcessContainer,Organization organization,CityLawAgency cityLawAgency) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.cityLawAgency = cityLawAgency;
        this.userAccount = cityLawAgency.getUserAccountDirectory().getUserAccountList().get(0);
        populateTable();
    }
    /**
     * 
     */
    private void populateTable(){
        DefaultTableModel defaultTableModel = (DefaultTableModel)caseTable.getModel();
        defaultTableModel.setRowCount(0);
        for (WorkRequest workRequest : organization.getWorkQueue().getWorkRequestList()){
                DrugCaseRequest drugCaseRequest = (DrugCaseRequest)workRequest;
                Object[] row = new Object[10];
                row[0] = drugCaseRequest;
                row[1] = drugCaseRequest.getPriority();
                row[2] = drugCaseRequest.getSender().getUsername();
                row[3] = drugCaseRequest.getRequestDate() == null ? ImplConst.EMPTY : ImplCommonUtil.getFormattedDate(drugCaseRequest.getRequestDate());
                row[4] = drugCaseRequest.getResolveDate() == null ? ImplConst.EMPTY : ImplCommonUtil.getFormattedDate(drugCaseRequest.getResolveDate());
                row[5] = drugCaseRequest.getStatus();
                row[6] = drugCaseRequest.getProduct();
                row[7] = drugCaseRequest.getProduct().getProductName();
                row[8] = ImplCommonUtil.getFormattedDate(drugCaseRequest.getProduct().getExpiryDate());
                row[9] = drugCaseRequest.getMessage();
                defaultTableModel.addRow(row);            
            }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewRequestDetails = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        caseTable = new javax.swing.JTable();
        takeLegalActionButton = new javax.swing.JButton();
        declineAction = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Manage Request Against Medication");

        viewRequestDetails.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        viewRequestDetails.setText("View Request Details");
        viewRequestDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRequestDetailsActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/back.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        caseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Case ID", "Priority", "Sender", "Request Date", "Resolve Date", "Status", "Medicine ID", "Medicine Name", "Medicine Expiry Date", "Problem"
            }
        ));
        jScrollPane1.setViewportView(caseTable);
        if (caseTable.getColumnModel().getColumnCount() > 0) {
            caseTable.getColumnModel().getColumn(7).setResizable(false);
            caseTable.getColumnModel().getColumn(9).setResizable(false);
        }

        takeLegalActionButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        takeLegalActionButton.setText("Take Legal Action");
        takeLegalActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeLegalActionButtonActionPerformed(evt);
            }
        });

        declineAction.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        declineAction.setText("Decline Action");
        declineAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addComponent(viewRequestDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(declineAction, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(takeLegalActionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewRequestDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(takeLegalActionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(declineAction, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void viewRequestDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRequestDetailsActionPerformed
        int selectedRow =  caseTable.getSelectedRow();
        if (selectedRow < 0 ){
            JOptionPane.showMessageDialog(null, "Please select the row from the list");
        } else {
            DrugCaseRequest drugCaseRequest = (DrugCaseRequest)caseTable.getValueAt(selectedRow, 0);            
            ViewRequestJPanel viewRequestJPanel =  new ViewRequestJPanel(userProcessContainer,drugCaseRequest,userAccount,cityLawAgency);
            userProcessContainer.add("ManageRequestsJPanel",viewRequestJPanel);
            CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);
        } 
        
    }//GEN-LAST:event_viewRequestDetailsActionPerformed

    private void takeLegalActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeLegalActionButtonActionPerformed
        int selectedRow =  caseTable.getSelectedRow();
        if (selectedRow < 0 ){
            JOptionPane.showMessageDialog(null, "Please select the row from the list");
        } else {
            DrugCaseRequest drugCaseRequest = (DrugCaseRequest)caseTable.getValueAt(selectedRow, 0);            
            if(drugCaseRequest.getStatus().equals(ImplConst.CASE_NEW)){
                drugCaseRequest.setStatus(ImplConst.CASE_APPROVED);
                drugCaseRequest.setResolveDate(ImplCommonUtil.getTodaysDateBYDATE());
                Product product = (Product)caseTable.getValueAt(selectedRow, 6);
                ProductCase productCase =  product.getProductCaseCatalog().addProductCase();
                productCase.setDrugCaseRequest(drugCaseRequest);
                productCase.setCaseId(drugCaseRequest.getWorkRequestId());
                productCase.setCaseDescription(drugCaseRequest.getDescription());
                productCase.setPerson(drugCaseRequest.getSender().getPerson());
                if (drugCaseRequest.getPriority().equals(ImplConst.PRIORITY_CRITICAL)){
                    try {
                        SendNotificationMail.sendWarningMail(cityLawAgency,productCase);
                    } catch (MessagingException ex) {
                        Logger.getLogger(ManageRequestAgainstMedicationJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                refresh();
            }
        } 
    }//GEN-LAST:event_takeLegalActionButtonActionPerformed
    
    private void declineActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineActionActionPerformed
        int selectedRow =  caseTable.getSelectedRow();
        if (selectedRow < 0 ){
            JOptionPane.showMessageDialog(null, "Please select the row from the list");
        } else {
            DrugCaseRequest drugCaseRequest = (DrugCaseRequest)caseTable.getValueAt(selectedRow, 0);
            if(drugCaseRequest.getStatus().equals(ImplConst.CASE_NEW)){
                drugCaseRequest.setStatus(ImplConst.CASE_DECLINED);
                drugCaseRequest.setResolveDate(ImplCommonUtil.getTodaysDateBYDATE());
                refresh();
            }
        }
    }//GEN-LAST:event_declineActionActionPerformed
    private void refresh(){
        populateTable();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTable caseTable;
    private javax.swing.JButton declineAction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton takeLegalActionButton;
    private javax.swing.JButton viewRequestDetails;
    // End of variables declaration//GEN-END:variables
}
