/*
 * Class : ViewRequestJPanel.java
 * Developer : Laksh Lumba
 * Reviewer :
 * Description : 
 * Created On : Nov 20, 2014, 4:53:27 PM
 * ---------------------------------------------------------------------------
 * Change History
 * Develper :
 * Reviwer :
 * Changed ON :
 * ---------------------------------------------------------------------------
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drugsupplychain.neu.css.gui.city.lawagency;

import drugsupplychain.neu.css.model.organization.lawAgencies.CityLawAgency;
import drugsupplychain.neu.css.model.product.Product;
import drugsupplychain.neu.css.model.product.ProductCase;
import drugsupplychain.neu.css.model.request.DrugCaseRequest;
import drugsupplychain.neu.css.model.user.UserAccount;
import drugsupplychain.neu.css.util.ImplCommonUtil;
import drugsupplychain.neu.css.util.ImplConst;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JPanel;

/**
 *
 * @author Laksh
 */
public class ViewRequestJPanel extends javax.swing.JPanel {
    private final JPanel userProcessContainer;
    private final DrugCaseRequest drugCaseRequest;
    private final UserAccount userAccount;
    private final CityLawAgency cityLawAgency;
    /**
     * Creates new form ViewRequestJPanel
     * @param userProcessContainer
     * @param drugCaseRequest
     * @param userAccount
     * @param cityLawAgency
     */
    public ViewRequestJPanel(JPanel userProcessContainer,DrugCaseRequest drugCaseRequest,UserAccount userAccount,CityLawAgency cityLawAgency) {
        initComponents();
        this.drugCaseRequest = drugCaseRequest;
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.cityLawAgency = cityLawAgency;
        populateValues();
    }
    private void populateValues(){
       caseIDTextField.setText(drugCaseRequest.getWorkRequestId());
       priorityTextField.setText(drugCaseRequest.getPriority());
       requestDateTextField.setText(ImplCommonUtil.getFormattedDate(drugCaseRequest.getRequestDate()));
       if (null != drugCaseRequest.getResolveDate()){
            resolveDateTextField.setText(ImplCommonUtil.getFormattedDate(drugCaseRequest.getResolveDate()));
       }
       statusTextField.setText(drugCaseRequest.getStatus());
       personIDTextField.setText(String.valueOf(drugCaseRequest.getSender().getPerson().getPersonId()));
       personNameTextField.setText(drugCaseRequest.getSender().getPerson().getName());
       medicineIDTextField.setText(drugCaseRequest.getProduct().getBarcode());
       medicineNameTextField.setText(drugCaseRequest.getProduct().getProductName());
       manufactureIDTextField.setText(drugCaseRequest.getProduct().getManufacturerId());
       maufactureDateTextField.setText(drugCaseRequest.getProduct().getManufacturerName());
       expiryDateTextField.setText(ImplCommonUtil.getFormattedDate(drugCaseRequest.getProduct().getExpiryDate()));
       problemCausedTextField.setText(drugCaseRequest.getProblem());
       lincenseNumberTextField.setText(drugCaseRequest.getProduct().getMedicineLincense().getLicenseNumber());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        caseIDTextField = new javax.swing.JTextField();
        priorityTextField = new javax.swing.JTextField();
        requestDateTextField = new javax.swing.JTextField();
        resolveDateTextField = new javax.swing.JTextField();
        statusTextField = new javax.swing.JTextField();
        personIDTextField = new javax.swing.JTextField();
        personNameTextField = new javax.swing.JTextField();
        medicineIDTextField = new javax.swing.JTextField();
        medicineNameTextField = new javax.swing.JTextField();
        manufactureIDTextField = new javax.swing.JTextField();
        maufactureDateTextField = new javax.swing.JTextField();
        expiryDateTextField = new javax.swing.JTextField();
        problemCausedTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        lincenseNumberTextField = new javax.swing.JTextField();
        takeLegalActionButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        declineAction = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("View Request Details");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Request ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("Priority");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("Person ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setText("Medicine ID");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setText("Medicine Name");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setText("Manufactured BY");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setText("Manufacturing Date");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel10.setText("Problem Caused by Medicine");

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel11.setText("Effected Person Name");

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel12.setText("Request Date");

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel13.setText("Resolve Date");

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel14.setText("Status");

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel15.setText("Expiry Date");

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel16.setText("License Number");

        takeLegalActionButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        takeLegalActionButton.setText("Take Legal Action");
        takeLegalActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeLegalActionButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/back.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        declineAction.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        declineAction.setText("Decline Action");
        declineAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel16))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(caseIDTextField)
                                    .addComponent(priorityTextField)
                                    .addComponent(requestDateTextField)
                                    .addComponent(resolveDateTextField)
                                    .addComponent(statusTextField)
                                    .addComponent(personIDTextField)
                                    .addComponent(personNameTextField)
                                    .addComponent(medicineIDTextField)
                                    .addComponent(medicineNameTextField)
                                    .addComponent(manufactureIDTextField)
                                    .addComponent(maufactureDateTextField)
                                    .addComponent(expiryDateTextField)
                                    .addComponent(problemCausedTextField)
                                    .addComponent(lincenseNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1)))
                .addContainerGap(293, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, Short.MAX_VALUE)
                .addComponent(declineAction, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(takeLegalActionButton)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(caseIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(priorityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(requestDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(resolveDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(personIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(personNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(medicineIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(medicineNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(manufactureIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(maufactureDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(expiryDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addComponent(problemCausedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(lincenseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(jLabel17))
                    .addComponent(declineAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(takeLegalActionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void declineActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineActionActionPerformed
        if(drugCaseRequest.getStatus().equals(ImplConst.CASE_NEW)){
            drugCaseRequest.setResolveDate(ImplCommonUtil.getTodaysDateBYDATE());
            drugCaseRequest.setStatus(ImplConst.CASE_DECLINED);
            drugCaseRequest.setReceiver(userAccount);
        } else {
            jLabel17.setText("Legal Action has already been taken against the drug. Legal Case Action Id is : " + drugCaseRequest.getWorkRequestId() + " Status " + drugCaseRequest.getStatus());
        }
    }//GEN-LAST:event_declineActionActionPerformed

    private void takeLegalActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeLegalActionButtonActionPerformed
        if(drugCaseRequest.getStatus().equals(ImplConst.CASE_NEW)){
            drugCaseRequest.setStatus(ImplConst.CASE_APPROVED);
            drugCaseRequest.setResolveDate(ImplCommonUtil.getTodaysDateBYDATE()); 
            Product product = drugCaseRequest.getProduct();
            ProductCase productCase = product.getProductCaseCatalog().addProductCase();
            productCase.setCaseId(drugCaseRequest.getWorkRequestId());
            productCase.setCaseDescription(drugCaseRequest.getDescription());
            productCase.setPerson(userAccount.getPerson());
            productCase.setDrugCaseRequest(drugCaseRequest);
            if (drugCaseRequest.getPriority().equals(ImplConst.PRIORITY_CRITICAL)){
                try {
                    SendNotificationMail.sendWarningMail(cityLawAgency,productCase);
                } catch (MessagingException ex) {
                    Logger.getLogger(ManageRequestAgainstMedicationJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            jLabel17.setText("Legal Action has been taken against the drug. Legal Case Action Id is : " + drugCaseRequest.getWorkRequestId() + " Status " + drugCaseRequest.getStatus());
        } else{
            jLabel17.setText("Legal Action has already been taken against the drug. Legal Case Action Id is : " + drugCaseRequest.getWorkRequestId() + " Status " + drugCaseRequest.getStatus());
        }
    }//GEN-LAST:event_takeLegalActionButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField caseIDTextField;
    private javax.swing.JButton declineAction;
    private javax.swing.JTextField expiryDateTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lincenseNumberTextField;
    private javax.swing.JTextField manufactureIDTextField;
    private javax.swing.JTextField maufactureDateTextField;
    private javax.swing.JTextField medicineIDTextField;
    private javax.swing.JTextField medicineNameTextField;
    private javax.swing.JTextField personIDTextField;
    private javax.swing.JTextField personNameTextField;
    private javax.swing.JTextField priorityTextField;
    private javax.swing.JTextField problemCausedTextField;
    private javax.swing.JTextField requestDateTextField;
    private javax.swing.JTextField resolveDateTextField;
    private javax.swing.JTextField statusTextField;
    private javax.swing.JButton takeLegalActionButton;
    // End of variables declaration//GEN-END:variables
}
