/*
 * Class : FDISystemAdminWorkAreaJPanel.java
 * Developer : Laksh Lumba
 * Reviewer :
 * Description : 
 * Created On : Nov 11, 2014, 11:45:15 PM
 * ---------------------------------------------------------------------------
 * Change History
 * Develper :
 * Reviwer :
 * Changed ON :
 * ---------------------------------------------------------------------------
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drugsupplychain.neu.css.gui.national.lawagency.FDI;

import drugsupplychain.neu.css.log.ImplLogger;
import drugsupplychain.neu.css.model.organization.lawAgencies.NationalLawAgency;
import drugsupplychain.neu.css.model.organization.lawAgencies.StateLawAgency;
import drugsupplychain.neu.css.model.organization.lawAgencies.StateLawAgencyDirectory;
import drugsupplychain.neu.css.model.request.LawAgencyCaseRequest;
import drugsupplychain.neu.css.model.request.WorkRequest;
import drugsupplychain.neu.css.util.ImplConst;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Laksh
 */
public class ManageStateFDISystemJPanel extends javax.swing.JPanel {
    private final JPanel userProcessContainer;
    private final StateLawAgencyDirectory stateLawAgencyDirectory;
    private final String countryName;
    private final NationalLawAgency nationalLawAgency;
    /**
     * Creates new form ManageStateFDISystemJPanel
     * @param userProcessContainer
     * @param nationalLawAgency
     */
    public ManageStateFDISystemJPanel(JPanel userProcessContainer,NationalLawAgency nationalLawAgency) {
        initComponents();
        ImplLogger.enterMethod();
        this.userProcessContainer = userProcessContainer;
        this.stateLawAgencyDirectory = nationalLawAgency.getStateLawAgencyDirectory();
        this.countryName = nationalLawAgency.getName();
        this.nationalLawAgency = nationalLawAgency;
        ImplLogger.exitMethod();
        populateTable();
        populateNotification();
        
    }
    /**
     * populate notification
     */
    private void populateNotification(){
        ImplLogger.enterMethod();
        int notification = 0;
        for (StateLawAgency stateLawAgency : stateLawAgencyDirectory.getStateLawAgencyList()){
            for(WorkRequest workRequest : stateLawAgency.getWorkQueue().getWorkRequestList()){
                LawAgencyCaseRequest lawAgencyCaseRequest = (LawAgencyCaseRequest)workRequest;
                if(lawAgencyCaseRequest.getCaseStatus().equals(ImplConst.CASE_NEW)){
                    notification++;
                }
            }      
        }
        notificationLabel.setText(String.valueOf(notification));
        ImplLogger.exitMethod();
    }
    /**
     * populate the table
     */
    private void populateTable(){
        ImplLogger.enterMethod();
        DefaultTableModel defaultTableModel = (DefaultTableModel)stateFDITable.getModel();
        defaultTableModel.setRowCount(0);
        for (StateLawAgency stateLawAgency : stateLawAgencyDirectory.getStateLawAgencyList()){
            Object[] row = new Object[4];
            row[0] = stateLawAgency;
            row[1] = stateLawAgency.getOrganizationID();
            row[2] = stateLawAgency.getCityLawAgencyDirectory().getCityLawAgencyList().size();
            row[3] = stateLawAgency.getWorkQueue().getWorkRequestList().size();
            defaultTableModel.addRow(row);            
        }
        ImplLogger.exitMethod();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        registerStateFDIButton = new javax.swing.JButton();
        maangeStateCaseButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        stateFDITable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        notificationLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Manage State FDI");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 230, -1));

        registerStateFDIButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        registerStateFDIButton.setText("Register State FDI");
        registerStateFDIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerStateFDIButtonActionPerformed(evt);
            }
        });
        add(registerStateFDIButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 180, 50));

        maangeStateCaseButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        maangeStateCaseButton.setText("Manage State Cases");
        maangeStateCaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maangeStateCaseButtonActionPerformed(evt);
            }
        });
        add(maangeStateCaseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 180, 50));

        stateFDITable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "State Name", "Id", "City FDIs", "Open Cases"
            }
        ));
        jScrollPane1.setViewportView(stateFDITable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 710, 170));

        backButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/back.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 110, 40));

        refreshButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/refresh.png"))); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.add(notificationLabel);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 20, 20));
    }// </editor-fold>//GEN-END:initComponents
    /**
     * register State FDI Button
     * @param evt 
     */
    private void registerStateFDIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerStateFDIButtonActionPerformed
       ImplLogger.enterMethod();
       RegisterStateFDIJPanel registerStateFDIJPanel = new RegisterStateFDIJPanel(userProcessContainer,stateLawAgencyDirectory,countryName);
       userProcessContainer.add("RegisterStateFDIJPanel",registerStateFDIJPanel);
       CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
       cardLayout.next(userProcessContainer);
       ImplLogger.exitMethod();
    }//GEN-LAST:event_registerStateFDIButtonActionPerformed
    /**
     * back button
     * @param evt 
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        ImplLogger.enterMethod();
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        ImplLogger.exitMethod();
    }//GEN-LAST:event_backButtonActionPerformed
    /**
     * refresh button
     * @param evt 
     */
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        ImplLogger.enterMethod();
        populateTable();
        populateNotification();
        ImplLogger.exitMethod();
    }//GEN-LAST:event_refreshButtonActionPerformed
    /**
     * manage state case button
     * @param evt 
     */
    private void maangeStateCaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maangeStateCaseButtonActionPerformed
        ImplLogger.enterMethod();
        int selectedRow =  stateFDITable.getSelectedRow();
        if (selectedRow < 0 ){
            JOptionPane.showMessageDialog(null, "Please select the row from the list");
        } else {
            StateLawAgency stateLawAgency = (StateLawAgency)stateFDITable.getValueAt(selectedRow, 0);
            ManageStateCasesJPanel manageStateCasesJPanel = new ManageStateCasesJPanel(userProcessContainer,stateLawAgency,nationalLawAgency);
            userProcessContainer.add("ManageStateCasesJPanel",manageStateCasesJPanel);
            CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);
        }
        ImplLogger.exitMethod();
    }//GEN-LAST:event_maangeStateCaseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton maangeStateCaseButton;
    private javax.swing.JLabel notificationLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton registerStateFDIButton;
    private javax.swing.JTable stateFDITable;
    // End of variables declaration//GEN-END:variables
}
