/*
 * Class : MainJFrame.java
 * Developer : Laksh Lumba
 * Reviewer :
 * Description : 
 * Created On : Nov 11, 2014, 11:27:53 PM
 * ---------------------------------------------------------------------------
 * Change History
 * Develper :
 * Reviwer :
 * Changed ON :
 * ---------------------------------------------------------------------------
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drugsupplychain.neu.css.gui;

import drugsupplychain.neu.css.log.ImplLogger;
import drugsupplychain.neu.css.model.FDI.FDISystem;
import drugsupplychain.neu.css.model.distributor.CityDistributor;
import drugsupplychain.neu.css.model.distributor.NationalDistributor;
import drugsupplychain.neu.css.model.distributor.RegionalDistributor;
import drugsupplychain.neu.css.model.distributor.StateDistributor;
import drugsupplychain.neu.css.model.organization.Organization;
import drugsupplychain.neu.css.model.organization.lawAgencies.CityLawAgency;
import drugsupplychain.neu.css.model.organization.lawAgencies.NationalLawAgency;
import drugsupplychain.neu.css.model.organization.lawAgencies.RegionalLawAgency;
import drugsupplychain.neu.css.model.organization.lawAgencies.StateLawAgency;
import drugsupplychain.neu.css.model.organization.pharmacompany.InterNationalPharmaceauticalCompany;
import drugsupplychain.neu.css.model.organization.pharmacompany.NationalPharmaceauticalCompany;
import drugsupplychain.neu.css.model.organization.pharmacompany.RegionalPharmaceauticalCompany;
import drugsupplychain.neu.css.model.organization.pharmacompany.StatePharmaceauticalCompany;
import drugsupplychain.neu.css.model.user.UserAccount;
import drugsupplychain.neu.css.util.database.DB4OUtil;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Laksh
 */
public class MainJFrame extends javax.swing.JFrame {

      /**
     * Creates new form MainJFrame
     */
    private final FDISystem fDISystem;
    private final DB4OUtil dB4OUtil = DB4OUtil.getInstance();
            
    public MainJFrame() {
        initComponents();
        fDISystem =  dB4OUtil.retrieveSystem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        usernameTextField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        userProcessContainer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(java.awt.SystemColor.textHighlight);
        jPanel1.setLayout(null);

        usernameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usernameTextField.setToolTipText("username");
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(usernameTextField);
        usernameTextField.setBounds(830, 40, 190, 21);

        loginButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/login.png"))); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton);
        loginButton.setBounds(830, 100, 120, 40);

        logoutButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/logout.png"))); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutButton);
        logoutButton.setBounds(970, 100, 120, 40);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel1.setText("Global Surveillance and Forensic System for Protecting Pharmaceutical Distribution Supply Chain");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 120, 800, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/Header.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 200);
        jPanel1.add(passwordTextField);
        passwordTextField.setBounds(830, 70, 190, 20);

        jSplitPane1.setLeftComponent(jPanel1);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        userProcessContainer.add(jLabel2, "card2");

        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1187, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
       ImplLogger.enterMethod();
       String username = usernameTextField.getText();
       String password = passwordTextField.getText();
       ImplLogger.info("Username " + username + " Password " + password);
       Organization organization1 = null;
       Organization higherOrganization = null;
       Organization nextHigherOrganization = null;
       Organization highestOrganization = null;
       UserAccount userAccount = fDISystem.getUserAccountDirectory().authenticateUser(username, password);
       if (userAccount == null){
            //check for login username International Pharmacompnay           
            for(InterNationalPharmaceauticalCompany interNationalPharmaceauticalCompany : fDISystem.getInterNationalPharmaceauticalCompanyDirectory().getInterNationalPharmaceauticalCompanyList()){
                userAccount = interNationalPharmaceauticalCompany.getUserAccountDirectory().authenticateUser(username, password);
                  if (userAccount != null) {
                        ImplLogger.info("InterNationalPharmaceauticalCompany Username " + username);
                        organization1 = interNationalPharmaceauticalCompany;
                        higherOrganization = fDISystem;
                        break;
                    }
            }             
            // check the login for the law agency and city level organization
            if (null == userAccount){
                 for(RegionalLawAgency regionalLawAgency :  fDISystem.getRegionalLawAgencyDirectory().getRegionalLawAgencyList()){
                     userAccount = regionalLawAgency.getUserAccountDirectory().authenticateUser(username, password);                
                     if (userAccount == null){
                        for (NationalLawAgency nationalLawAgency :  regionalLawAgency.getNationalLawAgencyDirectory().getNationalLawAgencyList()){
                             userAccount = nationalLawAgency.getUserAccountDirectory().authenticateUser(username, password);                        
                             if (userAccount == null){
                                 for (StateLawAgency stateLawAgency :  nationalLawAgency.getStateLawAgencyDirectory().getStateLawAgencyList()){
                                      userAccount = stateLawAgency.getUserAccountDirectory().authenticateUser(username, password);
                                      if (userAccount == null){
                                          for(CityLawAgency cityLawAgency : stateLawAgency.getCityLawAgencyDirectory().getCityLawAgencyList()){
                                               userAccount = cityLawAgency.getUserAccountDirectory().authenticateUser(username, password);
                                               if (userAccount == null){
                                                   for (Organization organization : cityLawAgency.getOrganizationDirectory().getOrganizationList()){
                                                         userAccount = organization.getUserAccountDirectory().authenticateUser(username, password);
                                                         if (userAccount != null){
                                                             ImplLogger.info("Organization userAccount " + userAccount);
                                                             organization1 = organization;
                                                             higherOrganization = cityLawAgency;
                                                             nextHigherOrganization = stateLawAgency;
                                                             highestOrganization = nationalLawAgency;
                                                             break;
                                                         }
                                                     }                 
                                               } else {
                                                   ImplLogger.info("cityLawAgency userAccount " + userAccount);
                                                   organization1 = cityLawAgency;
                                                   higherOrganization = stateLawAgency;
                                                   nextHigherOrganization = nationalLawAgency;
                                                   highestOrganization = regionalLawAgency;
                                                   break;
                                               } 
                                               if (userAccount != null){
                                                   break;
                                               }                                        
                                          }
                                      } else {
                                         ImplLogger.info("stateLawAgency userAccount " + userAccount);
                                         organization1 = stateLawAgency;
                                         higherOrganization = nationalLawAgency;
                                         nextHigherOrganization = regionalLawAgency;
                                         highestOrganization = fDISystem;
                                         break;
                                      }
                                      if (userAccount != null){
                                          break;
                                      }
                                 }
                             } else {
                                 ImplLogger.info("nationalLawAgency userAccount " + userAccount);
                                 organization1 = nationalLawAgency;
                                 higherOrganization = regionalLawAgency;
                                 nextHigherOrganization = fDISystem;
                                 break;
                             }
                             if (userAccount != null){
                                 break;
                             }
                        }                   
                     } else {
                         ImplLogger.info("regionalLawAgency userAccount " + userAccount);
                         organization1 = regionalLawAgency;
                         higherOrganization = fDISystem;
                         break;
                     }
                     if (userAccount != null){
                         break;
                     }
                 }
             }
             // LOGIN FOR DISTRIBUTOR AND Lower Level Pharma Company
             if (userAccount == null){
                     for(RegionalLawAgency regionalLawAgency :  fDISystem.getRegionalLawAgencyDirectory().getRegionalLawAgencyList()){
                        for (RegionalDistributor regionalDistributor :  regionalLawAgency.getRegionalDistributorDirectory().getRegionalDistributorList()){
                            userAccount = regionalDistributor.getUserAccountDirectory().authenticateUser(username, password);
                            if (userAccount != null){
                                ImplLogger.info("regionalDistributor userAccount " + userAccount);
                                organization1 = regionalDistributor;
                                higherOrganization = regionalLawAgency;
                                nextHigherOrganization = fDISystem;
                                break;
                            }
                        }  
                        if (userAccount == null){  
                            for (RegionalPharmaceauticalCompany regionalPharmaceauticalCompany :  regionalLawAgency.getRegionalPharmaceauticalCompanyDirectory().getRegionalPharmaceauticalCompanyList()){
                                userAccount = regionalPharmaceauticalCompany.getUserAccountDirectory().authenticateUser(username, password);
                                if (userAccount != null){
                                    ImplLogger.info("regionalPharmaceauticalCompany userAccount " + userAccount);
                                    organization1 = regionalPharmaceauticalCompany;
                                    higherOrganization = regionalLawAgency;
                                    nextHigherOrganization = fDISystem;
                                    break;
                                }
                            }
                        }
                        if (userAccount == null){  
                            for (NationalLawAgency nationalLawAgency :  regionalLawAgency.getNationalLawAgencyDirectory().getNationalLawAgencyList()){
                                for (NationalDistributor nationalDistributor :  nationalLawAgency.getNationalDistributorDirectory().getNationalDistributorList()){
                                    userAccount = nationalDistributor.getUserAccountDirectory().authenticateUser(username, password);
                                    if (userAccount != null){
                                        ImplLogger.info("nationalDistributor userAccount " + userAccount);
                                        organization1 = nationalDistributor;
                                        higherOrganization = nationalLawAgency;
                                        nextHigherOrganization = regionalLawAgency;
                                        highestOrganization = fDISystem;
                                        break;
                                    }
                                }
                                if (userAccount == null){
                                    for (NationalPharmaceauticalCompany nationalPharmaceauticalCompany :  nationalLawAgency.getNationalPharmaceauticalCompanyDirectory().getNationalPharmaceauticalCompanyList()){
                                        userAccount = nationalPharmaceauticalCompany.getUserAccountDirectory().authenticateUser(username, password);
                                        if (userAccount != null){
                                            ImplLogger.info("nationalPharmaceauticalCompany userAccount " + userAccount);
                                            organization1 = nationalPharmaceauticalCompany;
                                            higherOrganization = nationalLawAgency;
                                            nextHigherOrganization = regionalLawAgency;
                                            highestOrganization = fDISystem;
                                            break;
                                        }
                                    }
                                } 
                                if (userAccount == null){
                                    for(StateLawAgency stateLawAgency : nationalLawAgency.getStateLawAgencyDirectory().getStateLawAgencyList()) {
                                        for (StateDistributor stateDistributor :  stateLawAgency.getStateDistributorDirectory().getStateDistributorList()){
                                            userAccount = stateDistributor.getUserAccountDirectory().authenticateUser(username, password);
                                            if (userAccount != null){
                                                ImplLogger.info("stateDistributor userAccount " + userAccount);
                                                organization1 = stateDistributor;
                                                higherOrganization = stateLawAgency;
                                                nextHigherOrganization = nationalLawAgency;
                                                highestOrganization = regionalLawAgency;
                                                break;
                                            }
                                        } 
                                        if(userAccount == null) { 
                                            for (StatePharmaceauticalCompany statePharmaceauticalCompany :  stateLawAgency.getStatePharmaceauticalCompanyDirectory().getStatePharmaceauticalCompanyList()){
                                                userAccount = statePharmaceauticalCompany.getUserAccountDirectory().authenticateUser(username, password);
                                                if (userAccount != null){
                                                    ImplLogger.info("statePharmaceauticalCompany userAccount " + userAccount);
                                                    organization1 = statePharmaceauticalCompany;
                                                    higherOrganization = stateLawAgency;
                                                    nextHigherOrganization = nationalLawAgency;
                                                    highestOrganization = regionalLawAgency;
                                                    break;
                                                }
                                            }
                                        } 
                                        if(userAccount == null) {
                                            for(CityLawAgency cityLawAgency : stateLawAgency.getCityLawAgencyDirectory().getCityLawAgencyList()) {
                                                for (CityDistributor cityDistributor :  cityLawAgency.getCityDistributorDirectory().getCityDistributorList()){
                                                    userAccount = cityDistributor.getUserAccountDirectory().authenticateUser(username, password);
                                                    if (userAccount != null) {
                                                        ImplLogger.info("cityDistributor userAccount " + userAccount);
                                                        organization1 = cityDistributor;
                                                        higherOrganization = cityLawAgency;
                                                        nextHigherOrganization = stateLawAgency;
                                                        highestOrganization = nationalLawAgency;
                                                        break;
                                                    }
                                                }
                                                if (userAccount != null) {
                                                    break;
                                                } 
                                            }                                            
                                        }
                                        if (userAccount != null){
                                            break;
                                        } 
                                    } 
                                }  if (userAccount != null){
                                      break;
                                } 
                            }
                        } 
                        if (userAccount != null){
                            break;
                        }
                }
            }
            
       }if (userAccount == null){
                ImplLogger.info("userAccount not found");
                JOptionPane.showMessageDialog(null, "Please enter the valid user name");
        } else {
             userProcessContainer.removeAll();
             ImplLogger.info("UserAccount found");
             CardLayout layout = (CardLayout) userProcessContainer.getLayout();
             userProcessContainer.add("workArea", userAccount.getRole().createWorkArea(userProcessContainer, userAccount,organization1,higherOrganization,nextHigherOrganization,highestOrganization,fDISystem));
             layout.next(userProcessContainer);
             ImplLogger.exitMethod();
        }       
    }//GEN-LAST:event_loginButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        ImplLogger.enterMethod();
        userProcessContainer.removeAll();
        usernameTextField.setText(null);
        passwordTextField.setText(null);
        dB4OUtil.storeSystem(fDISystem);
        ImplLogger.exitMethod();
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JPanel userProcessContainer;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
