/*
 * Class : CreateNewMedicineJPanel.java
 * Developer : Laksh Lumba
 * Reviewer :
 * Description : 
 * Created On : Nov 13, 2014, 9:07:54 PM
 * ---------------------------------------------------------------------------
 * Change History
 * Develper :
 * Reviwer :
 * Changed ON :
 * ---------------------------------------------------------------------------
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drugsupplychain.neu.css.gui.common.pharmaco;

import drugsupplychain.neu.css.log.ImplLogger;
import drugsupplychain.neu.css.model.organization.pharmacompany.PharmaceauticalCompany;
import drugsupplychain.neu.css.model.person.Person;
import drugsupplychain.neu.css.model.product.Product;
import drugsupplychain.neu.css.model.product.TrackOrganization;
import drugsupplychain.neu.css.util.ImplCommonUtil;
import drugsupplychain.neu.css.util.ImplConst;
import drugsupplychain.neu.css.util.ImplValidationUtils;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Laksh
 */
public class CreateNewMedicineJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final PharmaceauticalCompany pharmaceauticalCompany;
    /**
     * Creates new form CreateNewMedicineJPanel
     * @param userProcessContainer
     * @param pharmaceauticalCompany
     */
    public CreateNewMedicineJPanel(JPanel userProcessContainer,PharmaceauticalCompany pharmaceauticalCompany) {
        initComponents();
        ImplLogger.enterMethod();
        this.userProcessContainer = userProcessContainer;
        this.pharmaceauticalCompany = pharmaceauticalCompany;
        ImplLogger.exitMethod();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Prescription = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        chemicalTextArea = new javax.swing.JTextArea();
        backButton = new javax.swing.JButton();
        addNewMedicineButton = new javax.swing.JButton();
        notRequiredRadioButton = new javax.swing.JRadioButton();
        requiredRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        dateChooser = new datechooser.beans.DateChooserCombo();
        jLabel4 = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Produce New Medicine");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Product Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setText("Expiry Date");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setText("Chemical Composition");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setText("Prescription Required");

        nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTextFieldKeyTyped(evt);
            }
        });

        chemicalTextArea.setColumns(20);
        chemicalTextArea.setRows(5);
        chemicalTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                chemicalTextAreaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(chemicalTextArea);

        backButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/back.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        addNewMedicineButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        addNewMedicineButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/Untitledicon.png"))); // NOI18N
        addNewMedicineButton.setText("Add New Medicine");
        addNewMedicineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewMedicineButtonActionPerformed(evt);
            }
        });

        Prescription.add(notRequiredRadioButton);
        notRequiredRadioButton.setSelected(true);
        notRequiredRadioButton.setText("Not Required");

        Prescription.add(requiredRadioButton);
        requiredRadioButton.setText("Required");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Quantity");

        quantityTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityTextFieldKeyTyped(evt);
            }
        });

        dateChooser.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                dateChooserOnSelectionChange(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("Price Per Medicine");

        priceTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addNewMedicineButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(notRequiredRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(requiredRadioButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(priceTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addComponent(quantityTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 157, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(notRequiredRadioButton)
                    .addComponent(requiredRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(addNewMedicineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * back button
     * @param evt 
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        ImplLogger.enterMethod();
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        ImplLogger.exitMethod();
    }//GEN-LAST:event_backButtonActionPerformed
    /**
     * add new medicine
     * @param evt 
     */
    private void addNewMedicineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewMedicineButtonActionPerformed
        ImplLogger.enterMethod();
        if (validateFields()){
            Product product = pharmaceauticalCompany.getProductCatalog().addProduct();
            product.setProductName(nameTextField.getText());
            product.setAvailable(Integer.parseInt(quantityTextField.getText()));
            product.setInitialQuantity(Integer.parseInt(quantityTextField.getText()));
            product.setChemicalComposition(new StringBuffer(chemicalTextArea.getText()));
            product.setExpiryDate(dateChooser.getSelectedDate().getTime());
            product.setManufacturerName(pharmaceauticalCompany.getName());
            Person person = pharmaceauticalCompany.getPersonDirectory().getPersonList().get(0);
            if (null != person){
                product.setManuFacturerEMAIL(person.getEmail());
            }
            product.setManufacturerId(String.valueOf(pharmaceauticalCompany.getOrganizationID()));
            product.setPrice(Integer.parseInt(priceTextField.getText()));
            if(Prescription.getSelection().equals(notRequiredRadioButton.getModel())){
               product.setIsPrescriptionRequired(false);
            } else {
                product.setIsPrescriptionRequired(true);
            }
            TrackOrganization trackOrganization = new TrackOrganization();
            trackOrganization.setOrganization(pharmaceauticalCompany);
            trackOrganization.setQuantity(Integer.parseInt(quantityTextField.getText()));
            trackOrganization.setPuchaseDate(ImplCommonUtil.getTodaysDate());
            product.getProductTracker().put(String.valueOf(pharmaceauticalCompany.getOrganizationID()), trackOrganization);
            product.setManufactureDate(ImplCommonUtil.getTodaysDateBYDATE());
            clearAll();
        }
        ImplLogger.exitMethod();
    }//GEN-LAST:event_addNewMedicineButtonActionPerformed

    private void nameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldKeyTyped
        nameTextField.setBackground(Color.white);
    }//GEN-LAST:event_nameTextFieldKeyTyped

    private void quantityTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityTextFieldKeyTyped
         quantityTextField.setBackground(Color.white);
    }//GEN-LAST:event_quantityTextFieldKeyTyped

    private void priceTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTextFieldKeyTyped
        priceTextField.setBackground(Color.white);
    }//GEN-LAST:event_priceTextFieldKeyTyped

    private void chemicalTextAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chemicalTextAreaKeyTyped
        chemicalTextArea.setBackground(Color.white);
    }//GEN-LAST:event_chemicalTextAreaKeyTyped

    private void dateChooserOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dateChooserOnSelectionChange
        dateChooser.setBackground(Color.white);
    }//GEN-LAST:event_dateChooserOnSelectionChange
     /**
     * validate the fields before submitting
     */
    private boolean validateFields(){
        ImplLogger.enterMethod();
        StringBuffer validationMessage = new StringBuffer();
        boolean isValidationPassed = true;
        if(ImplValidationUtils.isStringEmptyOrNull(nameTextField.getText())){
            validationMessage.append(ImplConst.VALIDATE_PRODUCT_NAME);
            validationMessage.append(ImplConst.NEXT_LINE);
            nameTextField.setBackground(Color.red);
            isValidationPassed = false;
        }
        if(ImplValidationUtils.isStringEmptyOrNull(chemicalTextArea.getText())){
            validationMessage.append(ImplConst.VALIDATE_PRODUCT_CHEMICAL_COMPOSITION);
            validationMessage.append(ImplConst.NEXT_LINE);
            chemicalTextArea.setBackground(Color.red);
            isValidationPassed = false;
        }
        if(!ImplValidationUtils.isInteger(quantityTextField.getText())){
            validationMessage.append(ImplConst.VALIDATE_PRODUCT_QUANTITY);
            validationMessage.append(ImplConst.NEXT_LINE);
            quantityTextField.setBackground(Color.red);
            isValidationPassed = false;
        }
        
        if(!ImplValidationUtils.isInteger(priceTextField.getText())){
            validationMessage.append(ImplConst.VALIDATE_PRODUCT_AVAILABLE);
            validationMessage.append(ImplConst.NEXT_LINE);
            priceTextField.setBackground(Color.red);
            isValidationPassed = false;
        }
        Calendar expiryDate = dateChooser.getSelectedDate();
        Calendar currentDate = Calendar.getInstance();
        if((expiryDate == null) || expiryDate.compareTo(currentDate) <= 0){
            validationMessage.append(ImplConst.VALIDATE_PRODUCT_EXPIRY_DATE);
            validationMessage.append(ImplConst.NEXT_LINE);
            dateChooser.setBackground(Color.red);
            isValidationPassed = false;
        }
        if(!isValidationPassed){
            JOptionPane.showMessageDialog(null,validationMessage);
        }
        ImplLogger.exitMethod();
        return isValidationPassed;
    }
    /**
     * clear all the text field
     */
    private void clearAll(){
        ImplLogger.enterMethod();
        nameTextField.setText(ImplConst.EMPTY);
        priceTextField.setText(ImplConst.EMPTY);
        quantityTextField.setText(ImplConst.EMPTY);
        chemicalTextArea.setText(ImplConst.EMPTY);
        ImplLogger.exitMethod();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Prescription;
    private javax.swing.JButton addNewMedicineButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextArea chemicalTextArea;
    private datechooser.beans.DateChooserCombo dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JRadioButton notRequiredRadioButton;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JRadioButton requiredRadioButton;
    // End of variables declaration//GEN-END:variables
}
