/*
 * Class : ManageDistributorProductJPanel.java
 * Developer : Laksh Lumba
 * Reviewer :
 * Description : 
 * Created On : Nov 12, 2014, 9:42:49 PM
 * ---------------------------------------------------------------------------
 * Change History
 * Develper :
 * Reviwer :
 * Changed ON :
 * ---------------------------------------------------------------------------
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drugsupplychain.neu.css.gui.common.lawAgency.distributor;

import drugsupplychain.neu.css.gui.common.panel.TrackMedicalDetailsJPanel;
import drugsupplychain.neu.css.gui.common.panel.ViewMedicineDetails;
import drugsupplychain.neu.css.log.ImplLogger;
import drugsupplychain.neu.css.model.organization.Organization;
import drugsupplychain.neu.css.model.product.Product;
import drugsupplychain.neu.css.model.product.ProductCatalog;
import drugsupplychain.neu.css.model.product.ProductItem;
import drugsupplychain.neu.css.util.ImplCommonUtil;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Laksh
 */
public class ManageDistributorProductJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final ProductCatalog productCatalog;
    private final Organization organization;
    /**
     * Creates new form ManageDistributorProductJPanel
     * @param userProcessContainer
     * @param productCatalog
     * @param organization
     */
    public ManageDistributorProductJPanel(JPanel userProcessContainer,ProductCatalog productCatalog,Organization organization) {
        initComponents();
        ImplLogger.enterMethod();
        this.userProcessContainer = userProcessContainer;
        this.productCatalog = productCatalog;
        this.organization = organization;
        populateProductTable();
        ImplLogger.exitMethod();
    }
    private void populateProductTable(){
        ImplLogger.enterMethod();
        DefaultTableModel defaultTableModel = (DefaultTableModel)productTable.getModel();
        defaultTableModel.setRowCount(0);
        for (ProductItem productItem : productCatalog.getProductItems()){
                Object[] row = new Object[5];
                row[0] = productItem.getProduct().getProductName();
                row[1] = productItem;
                row[2] = productItem.getProduct().getManufactureDate() == null ? null : ImplCommonUtil.getFormattedDate(productItem.getProduct().getManufactureDate()); 
                row[3] = productItem.getProduct().getExpiryDate() == null ? null : ImplCommonUtil.getFormattedDate(productItem.getProduct().getExpiryDate());
                row[4] = productItem.getProduct().getProductCaseCatalog().getProductCaseList().size();
                defaultTableModel.addRow(row);            
        }
        ImplLogger.exitMethod();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        viewMedicineButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        trackMedicineButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Manage Distributor Product");

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Product Id", "Manufacture Date", "Expiray Date", "Case Against Medication"
            }
        ));
        jScrollPane1.setViewportView(productTable);
        if (productTable.getColumnModel().getColumnCount() > 0) {
            productTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            productTable.getColumnModel().getColumn(1).setPreferredWidth(10);
            productTable.getColumnModel().getColumn(2).setPreferredWidth(40);
            productTable.getColumnModel().getColumn(3).setPreferredWidth(40);
            productTable.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        viewMedicineButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        viewMedicineButton.setText("View Product Details");
        viewMedicineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMedicineButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/back.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        trackMedicineButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        trackMedicineButton.setText("Track Medicine");
        trackMedicineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackMedicineButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(546, 546, 546))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(245, 245, 245)
                                    .addComponent(trackMedicineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(viewMedicineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trackMedicineButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(viewMedicineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        ImplLogger.enterMethod();
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        ImplLogger.exitMethod();
    }//GEN-LAST:event_backButtonActionPerformed

    private void viewMedicineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMedicineButtonActionPerformed
        ImplLogger.enterMethod();
        int selectedRow =  productTable.getSelectedRow();
        if (selectedRow < 0 ){
            JOptionPane.showMessageDialog(null, "Please select the row from the list");
        } else {
            ProductItem productItem = (ProductItem)productTable.getValueAt(selectedRow, 1);
            ImplLogger.info("Product " + productItem);
            ViewMedicineDetails viewMedicineDetails =  new ViewMedicineDetails(userProcessContainer,productItem.getProduct(),organization);
            userProcessContainer.add("ViewMedicineDetails",viewMedicineDetails);
            CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);
        }
        ImplLogger.exitMethod();
    }//GEN-LAST:event_viewMedicineButtonActionPerformed

    private void trackMedicineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackMedicineButtonActionPerformed
        ImplLogger.enterMethod();
        int selectedRow =  productTable.getSelectedRow();
        if (selectedRow < 0 ){
            JOptionPane.showMessageDialog(null, "Please select the row from the list");
        } else {
            ProductItem productItem = (ProductItem)productTable.getValueAt(selectedRow, 1);
            ImplLogger.info("Product " + productItem);
            TrackMedicalDetailsJPanel trackMedicalDetailsJPanel =  new TrackMedicalDetailsJPanel(userProcessContainer,productItem.getProduct());
            userProcessContainer.add("TrackMedicalDetailsJPanel",trackMedicalDetailsJPanel);
            CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);
        }
        ImplLogger.exitMethod();
    }//GEN-LAST:event_trackMedicineButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productTable;
    private javax.swing.JButton trackMedicineButton;
    private javax.swing.JButton viewMedicineButton;
    // End of variables declaration//GEN-END:variables
}
