/*
 * Class : ManageNationalFDISystemJPanel.java
 * Developer : Laksh Lumba
 * Reviewer :
 * Description : 
 * Created On : Nov 11, 2014, 11:45:15 PM
 * ---------------------------------------------------------------------------
 * Change History
 * Develper :
 * Reviwer :
 * Changed ON :
 * ---------------------------------------------------------------------------
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drugsupplychain.neu.css.gui.regional.lawagency.FDI;

import drugsupplychain.neu.css.log.ImplLogger;
import drugsupplychain.neu.css.model.organization.lawAgencies.NationalLawAgency;
import drugsupplychain.neu.css.model.organization.lawAgencies.NationalLawAgencyDirectory;
import drugsupplychain.neu.css.model.organization.lawAgencies.RegionalLawAgency;
import drugsupplychain.neu.css.model.request.LawAgencyCaseRequest;
import drugsupplychain.neu.css.model.request.WorkRequest;
import drugsupplychain.neu.css.util.ImplConst;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Laksh
 */
public class ManageNationalFDISystemJPanel extends javax.swing.JPanel {
    private final JPanel userProcessContainer;
    private final NationalLawAgencyDirectory nationalLawAgencyDirectory;
    private final RegionalLawAgency regionalLawAgency;            
    private final String regionName;
    /**
     * Creates new form ManageNationalFDISystemJPanel
     * @param userProcessContainer
     * @param regionalLawAgency
     */
    public ManageNationalFDISystemJPanel(JPanel userProcessContainer,RegionalLawAgency regionalLawAgency) {
        initComponents();
        ImplLogger.enterMethod();
        this.userProcessContainer = userProcessContainer;
        this.nationalLawAgencyDirectory = regionalLawAgency.getNationalLawAgencyDirectory();
        this.regionName = regionalLawAgency.getName();
        this.regionalLawAgency = regionalLawAgency;
        ImplLogger.exitMethod();
        populateTable();
        populateNotification();
        
    }
    /**
     * populate notification
     */
    private void populateNotification(){
        ImplLogger.enterMethod();
        int notification = 0;
        for (NationalLawAgency nationalLawAgency : nationalLawAgencyDirectory.getNationalLawAgencyList()){
            for(WorkRequest workRequest : nationalLawAgency.getWorkQueue().getWorkRequestList()){
                LawAgencyCaseRequest lawAgencyCaseRequest = (LawAgencyCaseRequest)workRequest;
                if(lawAgencyCaseRequest.getCaseStatus().equals(ImplConst.CASE_NEW)){
                    notification++;
                }
            }      
        }
        notificationLabel.setText(String.valueOf(notification));
        ImplLogger.exitMethod();
    }
    /**
     * populate the table
     */
    private void populateTable(){
        ImplLogger.enterMethod();
        DefaultTableModel defaultTableModel = (DefaultTableModel)nationalFDITable.getModel();
        defaultTableModel.setRowCount(0);
        for (NationalLawAgency nationalLawAgency : nationalLawAgencyDirectory.getNationalLawAgencyList()){
            Object[] row = new Object[4];
            row[0] = nationalLawAgency;
            row[1] = nationalLawAgency.getOrganizationID();
            row[2] = nationalLawAgency.getStateLawAgencyDirectory().getStateLawAgencyList().size();
            row[3] = nationalLawAgency.getWorkQueue().getWorkRequestList().size();
            defaultTableModel.addRow(row);            
        }
        ImplLogger.exitMethod();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageNationalFDIButton = new javax.swing.JButton();
        maangeNationalCasesButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nationalFDITable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        notificationLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Manage National FDI");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 230, -1));

        manageNationalFDIButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        manageNationalFDIButton.setText("Register National FDI");
        manageNationalFDIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNationalFDIButtonActionPerformed(evt);
            }
        });
        add(manageNationalFDIButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 180, 50));

        maangeNationalCasesButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        maangeNationalCasesButton.setText("Manage National Cases");
        maangeNationalCasesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maangeNationalCasesButtonActionPerformed(evt);
            }
        });
        add(maangeNationalCasesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 180, 50));

        nationalFDITable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nation Name", "Id", "State FDIs", "Open Cases"
            }
        ));
        jScrollPane1.setViewportView(nationalFDITable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 510, 170));

        backButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/back.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 110, 40));

        refreshButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/refresh.png"))); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.add(notificationLabel);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 20, 20));
    }// </editor-fold>//GEN-END:initComponents
    /**
     * manage national fdi
     * @param evt 
     */
    private void manageNationalFDIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNationalFDIButtonActionPerformed
       ImplLogger.enterMethod();
       RegisterNationalFDIJPanel registerNationalFDIJPanel = new RegisterNationalFDIJPanel(userProcessContainer,nationalLawAgencyDirectory,regionName);
       userProcessContainer.add("RegisterNationalFDIJPanel",registerNationalFDIJPanel);
       CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
       cardLayout.next(userProcessContainer);
       ImplLogger.exitMethod();
    }//GEN-LAST:event_manageNationalFDIButtonActionPerformed
    /**
     * back button
     * @param evt 
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        ImplLogger.enterMethod();
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        ImplLogger.exitMethod();
    }//GEN-LAST:event_backButtonActionPerformed
    /**
     * refresh button
     * @param evt 
     */
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        ImplLogger.enterMethod();
        populateTable();
        populateNotification();
        ImplLogger.exitMethod();
    }//GEN-LAST:event_refreshButtonActionPerformed
    /**
     * manage national cases
     * @param evt 
     */
    private void maangeNationalCasesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maangeNationalCasesButtonActionPerformed
        ImplLogger.enterMethod();
        int selectedRow =  nationalFDITable.getSelectedRow();
        if (selectedRow < 0 ){
            JOptionPane.showMessageDialog(null, "Please select the row from the list");
        } else {
            NationalLawAgency nationalLawAgency = (NationalLawAgency)nationalFDITable.getValueAt(selectedRow, 0);
            ManageNationalCasesJPanel manageNationalCasesJPanel = new ManageNationalCasesJPanel(userProcessContainer,nationalLawAgency,regionalLawAgency);
            userProcessContainer.add("ManageNationalCasesJPanel",manageNationalCasesJPanel);
            CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);
        } 
        ImplLogger.exitMethod();
    }//GEN-LAST:event_maangeNationalCasesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton maangeNationalCasesButton;
    private javax.swing.JButton manageNationalFDIButton;
    private javax.swing.JTable nationalFDITable;
    private javax.swing.JLabel notificationLabel;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables
}
