/*
 * Class : TrackMedicalDetailsJPanel.java
 * Developer : Laksh Lumba
 * Reviewer :
 * Description : 
 * Created On : Nov 13, 2014, 9:08:13 PM
 * ---------------------------------------------------------------------------
 * Change History
 * Develper :
 * Reviwer :
 * Changed ON :
 * ---------------------------------------------------------------------------
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drugsupplychain.neu.css.gui.common.panel;

import drugsupplychain.neu.css.log.ImplLogger;
import drugsupplychain.neu.css.model.organization.pharmacompany.PharmaceauticalCompany;
import drugsupplychain.neu.css.model.product.Product;
import drugsupplychain.neu.css.model.product.TrackOrganization;
import java.awt.CardLayout;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Laksh
 */
public class TrackMedicalDetailsJPanel extends javax.swing.JPanel {
    private final JPanel userProcessContainer;
    private final Product product;
    /**
     * Creates new form TrackMedicalDetailsJPanel
     * @param userProcessContainer
     * @param product
     */
    public TrackMedicalDetailsJPanel(JPanel userProcessContainer,Product product) {
        initComponents();
        ImplLogger.enterMethod();
        this.userProcessContainer = userProcessContainer;
        this.product = product;
        ImplLogger.exitMethod();
        populateTables();
    }
    /**
     * populate the tables
     */
    private void populateTables(){
       ImplLogger.enterMethod();
        populateProductionTable();
        populateSupplyTable();
       ImplLogger.exitMethod();
    }
    /**
     * populate production tables
     */
    private void populateProductionTable(){
        ImplLogger.enterMethod();
        DefaultTableModel defaultTableModel = (DefaultTableModel)productionDetailsTable.getModel();
        defaultTableModel.setRowCount(0);
        Set<Map.Entry<String, TrackOrganization>> entrySet = product.getProductTracker().entrySet();
        for (Entry entry : entrySet) {
           String id = (String) entry.getKey();
           TrackOrganization trackOrganization = (TrackOrganization) entry.getValue();
           if (trackOrganization.getOrganization() instanceof PharmaceauticalCompany){
                Object[] row = new Object[6];
                row[0] = trackOrganization.getPuchaseDate();
                row[1] = trackOrganization.getOrganization().getOrganizationID();
                row[2] = trackOrganization.getOrganization().getName();
                row[3] = product.getInitialQuantity();
                row[4] = trackOrganization.getOrganization().getLocation();
                row[5] = trackOrganization.getOrganization().getPersonDirectory().getPersonList().get(0).getAddress();
                defaultTableModel.addRow(row);
           }
        }
        ImplLogger.exitMethod();
    }
    /**
     * populate product supply tables
     */
    private void populateSupplyTable(){
        ImplLogger.enterMethod();
        DefaultTableModel defaultTableModel = (DefaultTableModel)supplyDetailsTable.getModel();
        defaultTableModel.setRowCount(0);
        Set<Map.Entry<String, TrackOrganization>> entrySet = product.getProductTracker().entrySet();
        for (Entry entry : entrySet) {
           String id = (String) entry.getKey();
           TrackOrganization trackOrganization = (TrackOrganization) entry.getValue();
           if (!(trackOrganization.getOrganization() instanceof PharmaceauticalCompany)){
                Object[] row = new Object[7];
                row[0] = trackOrganization.getPuchaseDate();
                row[1] = trackOrganization.getOrganization().getOrganizationID();
                row[2] = trackOrganization.getOrganization().getClass().getSimpleName();
                row[3] = trackOrganization.getOrganization().getName();
                row[4] = trackOrganization.getQuantity();
                row[5] = trackOrganization.getOrganization().getLocation();
                row[6] = trackOrganization.getOrganization().getPersonDirectory().getPersonList().get(0).getAddress();
                defaultTableModel.addRow(row);
           }
        }
        ImplLogger.exitMethod();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productionDetailsTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        supplyDetailsTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Product Track Details");

        productionDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produce Date", "Pharma ID", "Pharma Name", "Quantity Produced", "Location", "Organization Address"
            }
        ));
        jScrollPane1.setViewportView(productionDetailsTable);
        if (productionDetailsTable.getColumnModel().getColumnCount() > 0) {
            productionDetailsTable.getColumnModel().getColumn(5).setPreferredWidth(200);
        }

        supplyDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Purchase  Date", "Organization ID", "Organization Type", "Pharma Name", "Quantity Purchased", "Location", "Organization Address"
            }
        ));
        jScrollPane2.setViewportView(supplyDetailsTable);
        if (supplyDetailsTable.getColumnModel().getColumnCount() > 0) {
            supplyDetailsTable.getColumnModel().getColumn(6).setPreferredWidth(200);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Medicine Generation Details ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Medicine Supply chain Details ");

        backButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drugsupplychain/images/back.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        ImplLogger.enterMethod();
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        ImplLogger.exitMethod();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable productionDetailsTable;
    private javax.swing.JTable supplyDetailsTable;
    // End of variables declaration//GEN-END:variables
}
